# Generated by Django 2.0.dev20170803012132 on 2017-08-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170808_2007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
