# Generated by Django 2.0.dev20170803012132 on 2017-08-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170808_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '質問', 'verbose_name_plural': '質問の複数形'},
        ),
    ]
