# Generated by Django 2.0.dev20170803012132 on 2017-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170809_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date'], 'verbose_name': '質問', 'verbose_name_plural': '質問の複数形'},
        ),
    ]
